spring:
  application:
    name: sport-app
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root1234
    driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql=true:
      properties:
        hibernate:
          format_sql=true:
      database-platform: org.hibernate.dialect.H2Dialect

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl